# Generated by Django 4.1.5 on 2023-02-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('PM1', models.FloatField(verbose_name='PM1(ug/m3)')),
                ('PM10', models.FloatField(verbose_name='PM10(ug/m3)')),
                ('PM25', models.FloatField(verbose_name='PM2.5(ug/m3)')),
                ('RH', models.FloatField(verbose_name='RH(%)')),
                ('T', models.FloatField(verbose_name='T(C)')),
            ],
            options={
                'verbose_name': 'Device8',
                'verbose_name_plural': 'Device8 Data',
            },
        ),
    ]
